name: release-with-wasm
on:
  workflow_dispatch:
    inputs:
      wasmvmVer:
        description: 'set wasmvm version for image tagging'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            tkxkd0159/goreleaserx-wasm
          tags: |
            type=semver,pattern={{version}},value=${{ inputs.wasmvmVer }}
      -
        name: Build and push final images
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          file: ./docker/wasm.Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
