name: release
on:
  push:
    tags:
      - v*

env:
  GO111MODULE: on
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v3
      - run: git fetch --prune --unshallow
      -
        name: Setup env
        uses: c-py/action-dotenv-to-setenv@v3
        with:
          env-file: .env
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            tkxkd0159/goreleaserx
          tags: |
            type=semver,pattern={{version}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push base images
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          file: ./docker/final.Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            "GO_VERSION=${{env.GO_VERSION}}"
            "TINI_VERSION=${{env.TINI_VERSION}}"
            "GORELEASER_VERSION=${{env.GORELEASER_VERSION}}"
            "DEBIAN_FRONTEND=${{env.DEBIAN_FRONTEND}}"
            "OSX_SDK=${{env.OSX_SDK}}"
            "OSX_SDK_SUM=${{env.OSX_SDK_SUM}}"
            "OSX_VERSION_MIN=${{env.OSX_VERSION_MIN}}"
            "OSX_CROSS_COMMIT=${{env.OSX_CROSS_COMMIT}}"
